###
GET http://localhost:8080/api/technology

###
POST http://localhost:8080/api/technology

Content-Type: application/json

{
    "name": "React",
    "logo": "https://raw.githubusercontent.com/TevenV27/server-images/main/projects/technologies/react.png"
}
